CREATE TABLE runs (
    id INTEGER PRIMARY KEY,
    name TEXT,
    node_id TEXT,
    head_branch TEXT,
    head_sha TEXT,
    path TEXT,
    display_title TEXT,
    run_number INTEGER,
    event TEXT,
    status TEXT,
    conclusion TEXT,
    workflow_id INTEGER,
    check_suite_id INTEGER,
    check_suite_node_id TEXT,
    url TEXT,
    html_url TEXT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    actor TEXT,
    run_attempt INTEGER,
    referenced_workflows JSON,
    run_started_at TIMESTAMP,
    triggering_actor TEXT,
    jobs_url TEXT,
    logs_url TEXT,
    check_suite_url TEXT,
    artifacts_url TEXT,
    cancel_url TEXT,
    rerun_url TEXT,
    previous_attempt_url TEXT,
    workflow_url TEXT,
    repository TEXT,
    head_repository TEXT
);

CREATE TABLE jobs (
    id SERIAL PRIMARY KEY,
    jobName TEXT,
    sequence INTEGER,
    labelsRequested TEXT,
    runnerGroupRequested TEXT,
    runnerGroupMatched TEXT,
    runnerOS TEXT,
    runnerImage TEXT,
    runnerImageProvisioner TEXT,
    permissions JSON,
    startedAt TIMESTAMP,
    completedAt TIMESTAMP,
    conclusion TEXT,
    logs TEXT,
    run_id INTEGER REFERENCES runs(id)
);

CREATE TABLE steps (
    id SERIAL PRIMARY KEY,
    stepName TEXT,
    sequence INTEGER,
    action TEXT,
    run TEXT,
    startedAt TIMESTAMP,
    completedAt TIMESTAMP,
    conclusion TEXT,
    logs TEXT,
    job_id INTEGER REFERENCES jobs(id)
);