name: Checkov
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - 'terraform/**'
  pull_request:
    branches: ['main']
    paths:
      - 'terraform/**'
      
jobs:
  checkov:
      runs-on: ubuntu-latest
      steps:
      
      - name : Check out Git Repository
        uses: actions/checkout@v3
      
      - name: Run Checkov
        run: |
           docker run -t -v ${{ github.workspace }}/terraform:/tf --workdir /tf bridgecrew/checkov --directory /tf 
